server:
  port: 9393
spring:
  cloud:
    gateway:
      routes:
        - id: heroes-service
          uri: http://localhost:8080
          predicates:
            - Path=/heroes/**
        - id: httpbin
          uri: https://httpbin.org
          predicates:
            - Path=/httpbin/**
          filters:
            - StripPrefix=1
